# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Tue Jul 11 18:28:16 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(858, 849)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 851, 821))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.Ddata = QtGui.QPushButton(self.tab)
        self.Ddata.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.Ddata.setObjectName(_fromUtf8("Ddata"))
        self.Dredis = QtGui.QPushButton(self.tab)
        self.Dredis.setGeometry(QtCore.QRect(110, 30, 75, 23))
        self.Dredis.setObjectName(_fromUtf8("Dredis"))
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 70, 277, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.nick = QtGui.QLineEdit(self.layoutWidget1)
        self.nick.setObjectName(_fromUtf8("nick"))
        self.horizontalLayout.addWidget(self.nick)
        self.Duser = QtGui.QPushButton(self.layoutWidget1)
        self.Duser.setObjectName(_fromUtf8("Duser"))
        self.horizontalLayout.addWidget(self.Duser)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 20, 521, 341))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 211, 68))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_28 = QtGui.QLabel(self.layoutWidget2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_9.addWidget(self.label_28, 0, 0, 1, 1)
        self.lineEdit_ProgramID_2 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_ProgramID_2.setObjectName(_fromUtf8("lineEdit_ProgramID_2"))
        self.gridLayout_9.addWidget(self.lineEdit_ProgramID_2, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_9.addWidget(self.label_29, 1, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_9.addWidget(self.label_32, 2, 0, 1, 1)
        self.comboBox_EpisodeType = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_EpisodeType.setObjectName(_fromUtf8("comboBox_EpisodeType"))
        self.comboBox_EpisodeType.addItem(_fromUtf8(""))
        self.comboBox_EpisodeType.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_EpisodeType, 2, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 120, 496, 141))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.button_CreatePush = QtGui.QPushButton(self.layoutWidget3)
        self.button_CreatePush.setObjectName(_fromUtf8("button_CreatePush"))
        self.gridLayout_2.addWidget(self.button_CreatePush, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 1, 1, 1)
        self.button_CreatePush_heng = QtGui.QPushButton(self.layoutWidget3)
        self.button_CreatePush_heng.setObjectName(_fromUtf8("button_CreatePush_heng"))
        self.gridLayout_2.addWidget(self.button_CreatePush_heng, 1, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 1, 1, 1, 1)
        self.button_CreateAllGuess = QtGui.QPushButton(self.layoutWidget3)
        self.button_CreateAllGuess.setObjectName(_fromUtf8("button_CreateAllGuess"))
        self.gridLayout_2.addWidget(self.button_CreateAllGuess, 2, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 2, 1, 1, 1)
        self.button_CreateAllGuess_2 = QtGui.QPushButton(self.layoutWidget3)
        self.button_CreateAllGuess_2.setObjectName(_fromUtf8("button_CreateAllGuess_2"))
        self.gridLayout_2.addWidget(self.button_CreateAllGuess_2, 3, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 3, 1, 1, 1)
        self.button_CreateAllBase = QtGui.QPushButton(self.layoutWidget3)
        self.button_CreateAllBase.setObjectName(_fromUtf8("button_CreateAllBase"))
        self.gridLayout_2.addWidget(self.button_CreateAllBase, 4, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 261, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 177, 71))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_ProgramName = QtGui.QLabel(self.layoutWidget4)
        self.label_ProgramName.setObjectName(_fromUtf8("label_ProgramName"))
        self.gridLayout_5.addWidget(self.label_ProgramName, 0, 0, 1, 1)
        self.lineEdit_ProgramName = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_ProgramName.setObjectName(_fromUtf8("lineEdit_ProgramName"))
        self.gridLayout_5.addWidget(self.lineEdit_ProgramName, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 1, 1, 1, 1)
        self.button_CreateProgram = QtGui.QPushButton(self.layoutWidget4)
        self.button_CreateProgram.setObjectName(_fromUtf8("button_CreateProgram"))
        self.gridLayout_5.addWidget(self.button_CreateProgram, 2, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 160, 261, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 221, 163))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_EpisodeName_2 = QtGui.QLabel(self.layoutWidget5)
        self.label_EpisodeName_2.setObjectName(_fromUtf8("label_EpisodeName_2"))
        self.gridLayout_6.addWidget(self.label_EpisodeName_2, 4, 0, 1, 1)
        self.button_CreateEpisode_nomal = QtGui.QPushButton(self.layoutWidget5)
        self.button_CreateEpisode_nomal.setObjectName(_fromUtf8("button_CreateEpisode_nomal"))
        self.gridLayout_6.addWidget(self.button_CreateEpisode_nomal, 6, 0, 1, 2)
        self.label_ProgramID = QtGui.QLabel(self.layoutWidget5)
        self.label_ProgramID.setObjectName(_fromUtf8("label_ProgramID"))
        self.gridLayout_6.addWidget(self.label_ProgramID, 0, 0, 1, 1)
        self.button_CreateEpisode_live = QtGui.QPushButton(self.layoutWidget5)
        self.button_CreateEpisode_live.setObjectName(_fromUtf8("button_CreateEpisode_live"))
        self.gridLayout_6.addWidget(self.button_CreateEpisode_live, 6, 2, 1, 1)
        self.lineEdit_EpisodeName = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_EpisodeName.setObjectName(_fromUtf8("lineEdit_EpisodeName"))
        self.gridLayout_6.addWidget(self.lineEdit_EpisodeName, 2, 1, 1, 2)
        self.lineEdit_EpisodeTime = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_EpisodeTime.setObjectName(_fromUtf8("lineEdit_EpisodeTime"))
        self.gridLayout_6.addWidget(self.lineEdit_EpisodeTime, 4, 1, 1, 2)
        self.label_26 = QtGui.QLabel(self.layoutWidget5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 3, 1, 1, 2)
        self.lineEdit_ProgramID = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_ProgramID.setObjectName(_fromUtf8("lineEdit_ProgramID"))
        self.gridLayout_6.addWidget(self.lineEdit_ProgramID, 0, 1, 1, 2)
        self.label_EpisodeName = QtGui.QLabel(self.layoutWidget5)
        self.label_EpisodeName.setObjectName(_fromUtf8("label_EpisodeName"))
        self.gridLayout_6.addWidget(self.label_EpisodeName, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 1, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self.layoutWidget5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 5, 1, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 380, 261, 401))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.widget = QtGui.QWidget(self.groupBox_6)
        self.widget.setGeometry(QtCore.QRect(10, 20, 239, 365))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_EpisodeID = QtGui.QLabel(self.widget)
        self.label_EpisodeID.setObjectName(_fromUtf8("label_EpisodeID"))
        self.gridLayout.addWidget(self.label_EpisodeID, 0, 0, 1, 1)
        self.lineEdit_EpisodeID = QtGui.QLineEdit(self.widget)
        self.lineEdit_EpisodeID.setObjectName(_fromUtf8("lineEdit_EpisodeID"))
        self.gridLayout.addWidget(self.lineEdit_EpisodeID, 0, 1, 1, 3)
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_InfoName = QtGui.QLabel(self.widget)
        self.label_InfoName.setObjectName(_fromUtf8("label_InfoName"))
        self.gridLayout.addWidget(self.label_InfoName, 2, 0, 1, 1)
        self.lineEdit_InfoName = QtGui.QLineEdit(self.widget)
        self.lineEdit_InfoName.setObjectName(_fromUtf8("lineEdit_InfoName"))
        self.gridLayout.addWidget(self.lineEdit_InfoName, 2, 1, 1, 3)
        self.label_34 = QtGui.QLabel(self.widget)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 3, 1, 1, 3)
        self.label_PushType = QtGui.QLabel(self.widget)
        self.label_PushType.setObjectName(_fromUtf8("label_PushType"))
        self.gridLayout.addWidget(self.label_PushType, 4, 0, 1, 1)
        self.lineEdit_PushType = QtGui.QLineEdit(self.widget)
        self.lineEdit_PushType.setObjectName(_fromUtf8("lineEdit_PushType"))
        self.gridLayout.addWidget(self.lineEdit_PushType, 4, 1, 1, 3)
        self.label_24 = QtGui.QLabel(self.widget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 5, 1, 1, 3)
        self.label_PushType_2 = QtGui.QLabel(self.widget)
        self.label_PushType_2.setObjectName(_fromUtf8("label_PushType_2"))
        self.gridLayout.addWidget(self.label_PushType_2, 6, 0, 1, 1)
        self.lineEdit_productid = QtGui.QLineEdit(self.widget)
        self.lineEdit_productid.setObjectName(_fromUtf8("lineEdit_productid"))
        self.gridLayout.addWidget(self.lineEdit_productid, 6, 1, 1, 3)
        self.label_41 = QtGui.QLabel(self.widget)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 7, 1, 1, 3)
        self.label_PushType_3 = QtGui.QLabel(self.widget)
        self.label_PushType_3.setObjectName(_fromUtf8("label_PushType_3"))
        self.gridLayout.addWidget(self.label_PushType_3, 8, 0, 1, 1)
        self.lineEdit_articleid = QtGui.QLineEdit(self.widget)
        self.lineEdit_articleid.setObjectName(_fromUtf8("lineEdit_articleid"))
        self.gridLayout.addWidget(self.lineEdit_articleid, 8, 1, 1, 3)
        self.label_54 = QtGui.QLabel(self.widget)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout.addWidget(self.label_54, 9, 1, 1, 3)
        self.button_CreateStand_unlandscape = QtGui.QPushButton(self.widget)
        self.button_CreateStand_unlandscape.setObjectName(_fromUtf8("button_CreateStand_unlandscape"))
        self.gridLayout.addWidget(self.button_CreateStand_unlandscape, 10, 0, 1, 2)
        self.button_CreateStand_landscape = QtGui.QPushButton(self.widget)
        self.button_CreateStand_landscape.setObjectName(_fromUtf8("button_CreateStand_landscape"))
        self.gridLayout.addWidget(self.button_CreateStand_landscape, 10, 2, 1, 2)
        self.button_CreateArticle_unlandscape = QtGui.QPushButton(self.widget)
        self.button_CreateArticle_unlandscape.setObjectName(_fromUtf8("button_CreateArticle_unlandscape"))
        self.gridLayout.addWidget(self.button_CreateArticle_unlandscape, 11, 0, 1, 2)
        self.button_CreateArticle_landscape = QtGui.QPushButton(self.widget)
        self.button_CreateArticle_landscape.setObjectName(_fromUtf8("button_CreateArticle_landscape"))
        self.gridLayout.addWidget(self.button_CreateArticle_landscape, 11, 2, 1, 2)
        self.button_CreateGuess = QtGui.QPushButton(self.widget)
        self.button_CreateGuess.setObjectName(_fromUtf8("button_CreateGuess"))
        self.gridLayout.addWidget(self.button_CreateGuess, 12, 0, 1, 1)
        self.button_CreateVote = QtGui.QPushButton(self.widget)
        self.button_CreateVote.setObjectName(_fromUtf8("button_CreateVote"))
        self.gridLayout.addWidget(self.button_CreateVote, 12, 1, 1, 2)
        self.button_CreateProduct = QtGui.QPushButton(self.widget)
        self.button_CreateProduct.setObjectName(_fromUtf8("button_CreateProduct"))
        self.gridLayout.addWidget(self.button_CreateProduct, 12, 3, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.groupBox = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 251, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 30, 177, 71))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_ProgramName_2 = QtGui.QLabel(self.layoutWidget6)
        self.label_ProgramName_2.setObjectName(_fromUtf8("label_ProgramName_2"))
        self.gridLayout_4.addWidget(self.label_ProgramName_2, 0, 0, 1, 1)
        self.lineEdit_TopicName = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_TopicName.setObjectName(_fromUtf8("lineEdit_TopicName"))
        self.gridLayout_4.addWidget(self.lineEdit_TopicName, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.create_topic_button = QtGui.QPushButton(self.layoutWidget6)
        self.create_topic_button.setObjectName(_fromUtf8("create_topic_button"))
        self.gridLayout_4.addWidget(self.create_topic_button, 2, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 160, 251, 211))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.layoutWidget7 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 30, 219, 163))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.layoutWidget7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_TopicId = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_TopicId.setObjectName(_fromUtf8("lineEdit_TopicId"))
        self.gridLayout_3.addWidget(self.lineEdit_TopicId, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget7)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 1, 1, 1, 1)
        self.label_ProgramName_3 = QtGui.QLabel(self.layoutWidget7)
        self.label_ProgramName_3.setObjectName(_fromUtf8("label_ProgramName_3"))
        self.gridLayout_3.addWidget(self.label_ProgramName_3, 2, 0, 1, 1)
        self.lineEdit_TemplateName = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_TemplateName.setObjectName(_fromUtf8("lineEdit_TemplateName"))
        self.gridLayout_3.addWidget(self.lineEdit_TemplateName, 2, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget7)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.lineEdit_deadline = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEdit_deadline.setObjectName(_fromUtf8("lineEdit_deadline"))
        self.gridLayout_3.addWidget(self.lineEdit_deadline, 4, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget7)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_3.addWidget(self.label_38, 5, 1, 1, 1)
        self.create_template_button = QtGui.QPushButton(self.layoutWidget7)
        self.create_template_button.setObjectName(_fromUtf8("create_template_button"))
        self.gridLayout_3.addWidget(self.create_template_button, 6, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_10.setGeometry(QtCore.QRect(320, 20, 421, 351))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.layoutWidget8 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, 30, 201, 42))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_9 = QtGui.QLabel(self.layoutWidget8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_TopicId_2 = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_TopicId_2.setObjectName(_fromUtf8("lineEdit_TopicId_2"))
        self.gridLayout_8.addWidget(self.lineEdit_TopicId_2, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 1, 1, 1, 1)
        self.layoutWidget9 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget9.setGeometry(QtCore.QRect(20, 100, 365, 25))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget9)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.create_all_button_duel = QtGui.QPushButton(self.layoutWidget9)
        self.create_all_button_duel.setObjectName(_fromUtf8("create_all_button_duel"))
        self.gridLayout_14.addWidget(self.create_all_button_duel, 0, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget9)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_14.addWidget(self.label_48, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 20, 311, 221))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_14 = QtGui.QLabel(self.groupBox_11)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 270, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget10 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 60, 275, 141))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.gridLayout_15 = QtGui.QGridLayout(self.layoutWidget10)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.event_PushButton_duel = QtGui.QPushButton(self.layoutWidget10)
        self.event_PushButton_duel.setObjectName(_fromUtf8("event_PushButton_duel"))
        self.gridLayout_15.addWidget(self.event_PushButton_duel, 0, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget10)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_15.addWidget(self.label_49, 0, 1, 1, 1)
        self.event_PushButton_guess = QtGui.QPushButton(self.layoutWidget10)
        self.event_PushButton_guess.setObjectName(_fromUtf8("event_PushButton_guess"))
        self.gridLayout_15.addWidget(self.event_PushButton_guess, 1, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget10)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_15.addWidget(self.label_50, 1, 1, 1, 1)
        self.event_PushButton_like = QtGui.QPushButton(self.layoutWidget10)
        self.event_PushButton_like.setObjectName(_fromUtf8("event_PushButton_like"))
        self.gridLayout_15.addWidget(self.event_PushButton_like, 2, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget10)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_15.addWidget(self.label_51, 2, 1, 1, 1)
        self.event_PushButton_invite = QtGui.QPushButton(self.layoutWidget10)
        self.event_PushButton_invite.setObjectName(_fromUtf8("event_PushButton_invite"))
        self.gridLayout_15.addWidget(self.event_PushButton_invite, 3, 0, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget10)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_15.addWidget(self.label_52, 3, 1, 1, 1)
        self.event_PushButton_all = QtGui.QPushButton(self.layoutWidget10)
        self.event_PushButton_all.setObjectName(_fromUtf8("event_PushButton_all"))
        self.gridLayout_15.addWidget(self.event_PushButton_all, 4, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.layoutWidget10)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_15.addWidget(self.label_53, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 251, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget11 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 30, 177, 71))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget11)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_10 = QtGui.QLabel(self.layoutWidget11)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_MerchantName = QtGui.QLineEdit(self.layoutWidget11)
        self.lineEdit_MerchantName.setObjectName(_fromUtf8("lineEdit_MerchantName"))
        self.gridLayout_10.addWidget(self.lineEdit_MerchantName, 0, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget11)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_10.addWidget(self.label_44, 1, 1, 1, 1)
        self.button_CreateMerchant = QtGui.QPushButton(self.layoutWidget11)
        self.button_CreateMerchant.setObjectName(_fromUtf8("button_CreateMerchant"))
        self.gridLayout_10.addWidget(self.button_CreateMerchant, 2, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 160, 251, 161))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget12 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 30, 236, 117))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget12)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_4 = QtGui.QLabel(self.layoutWidget12)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_MerchantId = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEdit_MerchantId.setObjectName(_fromUtf8("lineEdit_MerchantId"))
        self.gridLayout_11.addWidget(self.lineEdit_MerchantId, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.layoutWidget12)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_11.addWidget(self.label_42, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget12)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_SPUname = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEdit_SPUname.setObjectName(_fromUtf8("lineEdit_SPUname"))
        self.gridLayout_11.addWidget(self.lineEdit_SPUname, 2, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget12)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_11.addWidget(self.label_43, 3, 1, 1, 1)
        self.button_CreateSPU = QtGui.QPushButton(self.layoutWidget12)
        self.button_CreateSPU.setObjectName(_fromUtf8("button_CreateSPU"))
        self.gridLayout_11.addWidget(self.button_CreateSPU, 4, 0, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 340, 251, 201))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.layoutWidget13 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 30, 236, 163))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget13)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_11 = QtGui.QLabel(self.layoutWidget13)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_MerchantId_2 = QtGui.QLineEdit(self.layoutWidget13)
        self.lineEdit_MerchantId_2.setObjectName(_fromUtf8("lineEdit_MerchantId_2"))
        self.gridLayout_13.addWidget(self.lineEdit_MerchantId_2, 0, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget13)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_13.addWidget(self.label_45, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget13)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_SPUId = QtGui.QLineEdit(self.layoutWidget13)
        self.lineEdit_SPUId.setObjectName(_fromUtf8("lineEdit_SPUId"))
        self.gridLayout_13.addWidget(self.lineEdit_SPUId, 2, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget13)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_13.addWidget(self.label_46, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget13)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_13.addWidget(self.label_13, 4, 0, 1, 1)
        self.lineEdit_Price = QtGui.QLineEdit(self.layoutWidget13)
        self.lineEdit_Price.setObjectName(_fromUtf8("lineEdit_Price"))
        self.gridLayout_13.addWidget(self.lineEdit_Price, 4, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget13)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_13.addWidget(self.label_47, 5, 1, 1, 1)
        self.button_CreateSKU = QtGui.QPushButton(self.layoutWidget13)
        self.button_CreateSKU.setObjectName(_fromUtf8("button_CreateSKU"))
        self.gridLayout_13.addWidget(self.button_CreateSKU, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.layoutWidget14 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget14.setGeometry(QtCore.QRect(730, 10, 99, 22))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget14)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_8 = QtGui.QLabel(self.layoutWidget14)
        self.label_8.setStyleSheet(_fromUtf8("alternate-background-color: rgb(255, 255, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.region_box = QtGui.QComboBox(self.layoutWidget14)
        self.region_box.setStyleSheet(_fromUtf8(""))
        self.region_box.setObjectName(_fromUtf8("region_box"))
        self.region_box.addItem(_fromUtf8(""))
        self.region_box.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.region_box, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Dredis, self.nick)
        MainWindow.setTabOrder(self.nick, self.Duser)
        MainWindow.setTabOrder(self.Duser, self.lineEdit_TopicName)
        MainWindow.setTabOrder(self.lineEdit_TopicName, self.create_topic_button)
        MainWindow.setTabOrder(self.create_topic_button, self.lineEdit_TopicId)
        MainWindow.setTabOrder(self.lineEdit_TopicId, self.lineEdit_TemplateName)
        MainWindow.setTabOrder(self.lineEdit_TemplateName, self.lineEdit_deadline)
        MainWindow.setTabOrder(self.lineEdit_deadline, self.create_template_button)
        MainWindow.setTabOrder(self.create_template_button, self.lineEdit_TopicId_2)
        MainWindow.setTabOrder(self.lineEdit_TopicId_2, self.create_all_button_duel)
        MainWindow.setTabOrder(self.create_all_button_duel, self.lineEdit_ProgramName)
        MainWindow.setTabOrder(self.lineEdit_ProgramName, self.button_CreateProgram)
        MainWindow.setTabOrder(self.button_CreateProgram, self.button_CreateEpisode_nomal)
        MainWindow.setTabOrder(self.button_CreateEpisode_nomal, self.button_CreateEpisode_live)
        MainWindow.setTabOrder(self.button_CreateEpisode_live, self.lineEdit_EpisodeName)
        MainWindow.setTabOrder(self.lineEdit_EpisodeName, self.lineEdit_EpisodeTime)
        MainWindow.setTabOrder(self.lineEdit_EpisodeTime, self.lineEdit_ProgramID)
        MainWindow.setTabOrder(self.lineEdit_ProgramID, self.lineEdit_ProgramID_2)
        MainWindow.setTabOrder(self.lineEdit_ProgramID_2, self.comboBox_EpisodeType)
        MainWindow.setTabOrder(self.comboBox_EpisodeType, self.lineEdit_EpisodeID)
        MainWindow.setTabOrder(self.lineEdit_EpisodeID, self.lineEdit_InfoName)
        MainWindow.setTabOrder(self.lineEdit_InfoName, self.lineEdit_PushType)
        MainWindow.setTabOrder(self.lineEdit_PushType, self.button_CreateGuess)
        MainWindow.setTabOrder(self.button_CreateGuess, self.button_CreateStand_unlandscape)
        MainWindow.setTabOrder(self.button_CreateStand_unlandscape, self.button_CreateVote)
        MainWindow.setTabOrder(self.button_CreateVote, self.button_CreateStand_landscape)
        MainWindow.setTabOrder(self.button_CreateStand_landscape, self.button_CreatePush)
        MainWindow.setTabOrder(self.button_CreatePush, self.button_CreatePush_heng)
        MainWindow.setTabOrder(self.button_CreatePush_heng, self.button_CreateAllGuess)
        MainWindow.setTabOrder(self.button_CreateAllGuess, self.button_CreateAllGuess_2)
        MainWindow.setTabOrder(self.button_CreateAllGuess_2, self.button_CreateAllBase)
        MainWindow.setTabOrder(self.button_CreateAllBase, self.Ddata)
        MainWindow.setTabOrder(self.Ddata, self.lineEdit_productid)
        MainWindow.setTabOrder(self.lineEdit_productid, self.button_CreateProduct)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "测试工具", None))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.Ddata.setText(_translate("MainWindow", "清空数据库", None))
        self.Dredis.setText(_translate("MainWindow", "清空redis", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>昵称：</p></body></html>", None))
        self.Duser.setText(_translate("MainWindow", "删除user", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "清理重建", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "批量创建", None))
        self.label_28.setText(_translate("MainWindow", "program id：", None))
        self.label_29.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_29.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">*不填新建一个program</span></p></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "类型：", None))
        self.comboBox_EpisodeType.setItemText(0, _translate("MainWindow", "非直播", None))
        self.comboBox_EpisodeType.setItemText(1, _translate("MainWindow", "直播", None))
        self.button_CreatePush.setText(_translate("MainWindow", "推送", None))
        self.label_27.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">2分钟后开播：4个null，2个及时，0s,10s,20s...140s</span></p></body></html>", None))
        self.button_CreatePush_heng.setText(_translate("MainWindow", "横屏推送", None))
        self.label_35.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">2分钟后开播</span></p></body></html>", None))
        self.button_CreateAllGuess.setText(_translate("MainWindow", "竞猜1", None))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">不参与，输，赢，赢0分</span></p></body></html>", None))
        self.button_CreateAllGuess_2.setText(_translate("MainWindow", "竞猜2", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">9种状态全</span></p></body></html>", None))
        self.button_CreateAllBase.setText(_translate("MainWindow", "info基本项", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">info（标题，问题描述，推送时间标）检测</span></p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "创建program", None))
        self.label_ProgramName.setText(_translate("MainWindow", "名字：", None))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.button_CreateProgram.setText(_translate("MainWindow", "创建program", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "创建episode", None))
        self.label_EpisodeName_2.setText(_translate("MainWindow", "*分钟过期：", None))
        self.button_CreateEpisode_nomal.setText(_translate("MainWindow", "非直播episode", None))
        self.label_ProgramID.setText(_translate("MainWindow", "program id：", None))
        self.button_CreateEpisode_live.setText(_translate("MainWindow", "直播episode", None))
        self.label_26.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_26.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_EpisodeName.setText(_translate("MainWindow", "名字：", None))
        self.label_22.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_22.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填新建一个program</span></p></body></html>", None))
        self.label_33.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_33.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认1分钟</span></p></body></html>", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "创建info", None))
        self.label_EpisodeID.setText(_translate("MainWindow", "episode id：", None))
        self.label_23.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_23.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">*必填</span></p></body></html>", None))
        self.label_InfoName.setText(_translate("MainWindow", "名字：", None))
        self.label_34.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_34.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_PushType.setText(_translate("MainWindow", "推送：", None))
        self.label_24.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_24.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填：offset为null</span></p><p><span style=\" color:#8f8f8f;\">*数字：offset=数字</span></p><p><span style=\" color:#8f8f8f;\">*及时：及时推送</span></p></body></html>", None))
        self.label_PushType_2.setText(_translate("MainWindow", "SPU id：", None))
        self.label_41.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_41.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认第一个，没有新建</span></p></body></html>", None))
        self.label_PushType_3.setText(_translate("MainWindow", "article id：", None))
        self.label_54.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_54.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认第一个，没有新建</span></p></body></html>", None))
        self.button_CreateStand_unlandscape.setText(_translate("MainWindow", "图文-无横屏", None))
        self.button_CreateStand_landscape.setText(_translate("MainWindow", "图文-有横屏", None))
        self.button_CreateArticle_unlandscape.setText(_translate("MainWindow", "文章-无横屏", None))
        self.button_CreateArticle_landscape.setText(_translate("MainWindow", "文章-有横屏", None))
        self.button_CreateGuess.setText(_translate("MainWindow", "竞猜", None))
        self.button_CreateVote.setText(_translate("MainWindow", "投票", None))
        self.button_CreateProduct.setText(_translate("MainWindow", "商品", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "program", None))
        self.groupBox.setTitle(_translate("MainWindow", "创建topic", None))
        self.label_ProgramName_2.setText(_translate("MainWindow", "名字：", None))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.create_topic_button.setText(_translate("MainWindow", "创建topic", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "创建template", None))
        self.label_6.setText(_translate("MainWindow", "topic id：", None))
        self.label_37.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_37.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">*不填新建一个topic</span></p></body></html>", None))
        self.label_ProgramName_3.setText(_translate("MainWindow", "名字：", None))
        self.label_39.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_39.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "*分钟后过期：", None))
        self.label_38.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_38.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认1分钟</span></p></body></html>", None))
        self.create_template_button.setText(_translate("MainWindow", "创建template", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "批量创建", None))
        self.label_9.setText(_translate("MainWindow", "topic id：", None))
        self.label_40.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_40.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">*不填新建一个topic</span></p></body></html>", None))
        self.create_all_button_duel.setText(_translate("MainWindow", "创建all", None))
        self.label_48.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>10个template（2,4,6...18,20分钟后过期）</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "duel", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "批量创建", None))
        self.label_14.setText(_translate("MainWindow", "以下均包含3个时段：已经结束，活动中，还未开始", None))
        self.event_PushButton_duel.setText(_translate("MainWindow", "duel", None))
        self.label_49.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p>只按duel产生的分数排名</p></body></html>", None))
        self.event_PushButton_guess.setText(_translate("MainWindow", "guess", None))
        self.label_50.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p>只按guess产生的分数排名</p></body></html>", None))
        self.event_PushButton_like.setText(_translate("MainWindow", "like", None))
        self.label_51.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p>只按like产生的分数排名</p></body></html>", None))
        self.event_PushButton_invite.setText(_translate("MainWindow", "invite", None))
        self.label_52.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p>只按invite产生的分数排名</p></body></html>", None))
        self.event_PushButton_all.setText(_translate("MainWindow", "all", None))
        self.label_53.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#909090;\">1111</span></p></body></html>", None))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p>按任何方式产生的分数，都计入排名</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "event", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "创建店铺", None))
        self.label_10.setText(_translate("MainWindow", "名字：", None))
        self.label_44.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_44.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.button_CreateMerchant.setText(_translate("MainWindow", "创建店铺", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "创建SPU", None))
        self.label_4.setText(_translate("MainWindow", "merchant id：", None))
        self.label_42.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_42.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认第一个，没有新建</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "名字：", None))
        self.label_43.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_43.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填使用随机名字</span></p></body></html>", None))
        self.button_CreateSPU.setText(_translate("MainWindow", "创建SPU", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "创建SKU", None))
        self.label_11.setText(_translate("MainWindow", "merchant id：", None))
        self.label_45.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_45.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认第一个，没有新建</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "SPU id：", None))
        self.label_46.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_46.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认第一个，没有新建</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "价格：", None))
        self.label_47.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">111</span></p></body></html>", None))
        self.label_47.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">*不填使用随机名字</span></p></body></html>", None))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#8f8f8f;\">*不填默认200</span></p></body></html>", None))
        self.button_CreateSKU.setText(_translate("MainWindow", "创建SKU", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "merchant", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">测试环境</span></p></body></html>", None))
        self.region_box.setItemText(0, _translate("MainWindow", "cn", None))
        self.region_box.setItemText(1, _translate("MainWindow", "id", None))

